"use client";

import { useState } from "react";
import styles from "./ArtifactSection.module.css";

const artifactSections = [
  {
    title: "Opportunity map",
    description: "Interventions ranked by value, feasibility, required access, and what it takes to govern.",
    status: "complete",
  },
  {
    title: "Workflow analysis",
    description: "How the work actually moves today — the handoffs, the waits, the coordination nobody planned for.",
    status: "complete",
  },
  {
    title: "Required controls",
    description: "The permissions, approval gates, data boundaries, and audit trail each intervention needs.",
    status: "complete",
  },
  {
    title: "Human and agent responsibilities",
    description: "Who decides, who executes, who reviews — spelled out before anything ships.",
    status: "complete",
  },
  {
    title: "Deployment plan",
    description: "The sequence, the environment, the integrations, and the first bounded capability we'll ship.",
    status: "complete",
  },
  {
    title: "Measurement plan",
    description: "The baseline, the target, and how we'll know it's actually working.",
    status: "complete",
  },
];

export function ArtifactSection() {
  const [activeCell, setActiveCell] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText("# Opportunity and Readiness Map\n\nArtifact generated by Splice Works assessment...");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className={styles.section} id="artifact">
      <div className={styles.left}>
        <span className={styles.num} aria-hidden="true">01</span>
        <p className={styles.eyebrow}>
          <b>First-run output</b>
          <span>artifact preview · sample</span>
        </p>
        <h2 className={styles.heading}>
          Leave with a decision, not a deck.
        </h2>
        <p className={styles.sub}>
          The first assessment hands you an inspectable artifact — every
          section carries its sources, its assumptions, and the approvals
          it would need.
        </p>
      </div>
      <div className={styles.artifact}>
        <div className={styles.artifactHeader}>
          <div>
            <span className={styles.meta}>artifact · sample · v1 · assessment</span>
            <h3 className={styles.artifactTitle}>Opportunity and readiness map</h3>
          </div>
          <div className={styles.headerRight}>
            <span className={styles.tagComplete}>
              <span className={styles.dot} />
              completed
            </span>
            <span className={styles.runId}>run_01HX…9F</span>
          </div>
        </div>
        <div className={styles.artifactBody}>
          {artifactSections.map((section, i) => (
            <button
              key={section.title}
              type="button"
              className={`${styles.artifactCell} ${activeCell === i ? styles.cellActive : ""}`}
              onClick={() => setActiveCell(activeCell === i ? null : i)}
              aria-expanded={activeCell === i}
            >
              <div className={styles.cellHeader}>
                <h4>{section.title}</h4>
              </div>
              <p>{section.description}</p>
              {activeCell === i && (
                <div className={styles.cellExpanded}>
                  <div className={styles.evidence}>
                    <span className={styles.evidenceLabel}>Evidence fragments</span>
                    <div className={styles.evidenceBars}>
                      <span style={{ width: "80%" }} />
                      <span style={{ width: "60%" }} />
                      <span style={{ width: "45%" }} />
                    </div>
                  </div>
                  <span className={styles.cellMeta}>3 sources · 1 approval</span>
                </div>
              )}
            </button>
          ))}
        </div>
        <div className={styles.artifactFooter}>
          <span className={styles.meta}>
            <span className={styles.provDot} />
            provenance verified · 7 evidence fragments · 1 approval
          </span>
          <div className={styles.actions}>
            <button className={styles.btn} onClick={handleCopy}>
              {copied ? "Copied!" : "Copy summary"}
            </button>
            <button className={styles.btn}>Download .md</button>
            <button className={`${styles.btn} ${styles.btnPrimary}`}>View full artifact</button>
          </div>
        </div>
      </div>
    </section>
  );
}
